server:
  port: 3000

spring:
  application:
    name: publishing-house-service
  cloud:
    aws:
      credentials:
        access-key: test
        secret-key: test
      sns:
        endpoint: http://localhost:4566

app:
  topic-name: book-topic

springdoc:
  swagger-ui:
    path: /swagger-ui
  group-configs:
    - group: v1
      paths-to-match:
        - /v1/**
    - group: v2
      paths-to-match:
        - /v2/**

debug: true