server:
  port: 3000

spring:
  application:
    name: publishing-house-service
  cloud:
    aws:
      credentials:
        access-key: test
        secret-key: test
      sns:
        endpoint: http://localhost:4566

app:
  topic-name: book-topic

springdoc:
  swagger-ui:
    path: /swagger-ui

debug: true